# примеры API-запросов

@baseUrl = http://127.0.0.1:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token f6e709144e95a192fedbb2791020776ee1ba86cc

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/4/
Content-Type: application/json
Authorization: Token f6e709144e95a192fedbb2791020776ee1ba86cc

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=1
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2024-10-01
Content-Type: application/json

###

# статус
GET {{baseUrl}}/advertisements/?status=CLOSED
Content-Type: application/json

###

# DELETE
DELETE {{baseUrl}}/advertisements/49/
Content-Type: application/json
Authorization: Token f6e709144e95a192fedbb2791020776ee1ba86cc